# Optional bot config.
# [bot]
# Admin user. (Optional)
# admin = "@example:example.org"

[command]
# The command prefix.
prefix = "%%"

[matrix]
# Homeserver URL.
homeserver = "https://matrix.example.com"
# Timeout of homeserver connection, measured in seconds.
# Defaults to 300 seconds (5 minutes).
# timeout = 300

# Service configurations.
[services.hitokoto]
# Hitokoto API base URL.
# base-url = "https://v1.hitokoto.cn"
[services.github]
# GitHub API Base URL. In most cases should not be changed.
# base-url = "https://api.github.com"
# Token used by GitHub API.
# See https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api
token = ""
[services.github.pr-tracker.targets.'NixOS/nixpkgs']
'\Astaging\z' = ["staging-next"]
'\Astaging-next\z' = ["master"]
'\Astaging-next-([\d.]+)\z' = ["release-$1"]
'\Ahaskell-updates\z' = ["staging"]
'\Amaster\z' = ["nixpkgs-unstable", "nixos-unstable-small"]
'\Anixos-(.*)-small\z' = ["nixos-$1"]
'\Arelease-([\d.]+)\z' = ["nixos-$1-small", "nixpkgs-$1-darwin"]
'\Astaging-((1.|20)\.\d{2})\z' = ["release-$1"]
'\Astaging-((2[1-9]|[3-90].)\.\d{2})\z' = ["staging-next-$1"]
'\Astaging-nixos\z' = ["master"]

[pixiv]
enabled = false
r18 = false
token = "????????_XXXXXXXXXXXXXXXXXXXX"

[[pixiv.tag-triggers]]
rooms = ["!XXXXXXXXXXX:example.org"]
required-tags = []
target = ""

[[pixiv.tag-triggers]]
required-tags = []
target = ""

[[features]]
room = ""
jerryxiao = true
fortune = false
pixiv = false
pixiv-r18 = false
