# Admin user. (Optional)
admin-user = "@example:example.org"

[command]
# The command prefix.
prefix = "%%"

[matrix]
# Homeserver URL.
homeserver = "https://matrix.example.com"
# Timeout of homeserver connection, measured in seconds.
# Defaults to 300 seconds (5 minutes).
# timeout = 300

# Service URLs.
[services]
# Hitokoto API.
hitokoto = "https://v1.hitokoto.cn"

[pixiv]
enabled = false
r18 = false
token = "????????_XXXXXXXXXXXXXXXXXXXX"

[[pixiv.traps]]
rooms = ["!XXXXXXXXXXX:example.org"]
required-tags = []
target = ""

[[pixiv.traps]]
required-tags = []
target = ""

[[features]]
room = ""
jerryxiao = true
fortune = false
pixiv = false
pixiv-r18 = false

[stickers]
send-to = "!XXXXXXXXXXX:example.org"

[nixpkgs-pr]
token = ""
